# frozen_string_literal: true

source 'https://rubygems.org'

# debugger
gem 'pry-byebug', '~> 3.10'

# static analyser
gem 'rubocop', '~> 1.36'

# test framework
gem 'rspec', '~> 3.11'
# for integration
gem 'selenium-webdriver', '~> 4.5'
# installer of the drivers
gem 'webdrivers', '~> 5.2'

# framework + application server
gem 'sinatra', '~> 3.0'
gem 'webrick', '~> 1.7'

# views template
gem 'slim', '~> 4.1'
