# frozen_string_literal: true

source 'https://rubygems.org'

# debugger
gem 'pry-byebug', '3.7.0'

# static analyser
gem 'rubocop', '0.66.0'

# test framework
gem 'rspec', '3.8.0'
# for integration
gem 'selenium-webdriver', '3.141.0'
# installer of the drivers
gem 'webdrivers', '3.8.0'

# framework
gem 'sinatra', '2.2.0'
